[tool.black]
line-length = 88
skip-string-normalization = false
target-version = ['py311']

[tool.pytest.ini_options]
addopts = "-ra -q"
minversion = "7.0"
testpaths = [
  "src",
]

[tool.ruff]
exclude = ["venv", "__pycache__"]
line-length = 88
lint.select = ["E", "F"] # basic pyflakes + pycodestyle
